apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
        tier: backend
        track: stable
    spec:
      containers:
        - name: customer
          image: "grajamca/customer:1.0.0"
          ports:
            - name: customer
              containerPort: 9111
          env:
            - name: USER_URL
              valueFrom:
                configMapKeyRef:
                  name: customer-config
                  key:  user_url
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
data:
  user_url: "http://user:8112/user/1"
---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
    tier: backend
  ports:
    - protocol: TCP
      port: 8111
      targetPort: customer